config/routes.rb
Bosa::Application.routes.draw do |map|

  devise_for :users, :controllers  => {:registrations  => "registrations", :sessions  => "sessions", :passwords  => "passwords"}, :path_names  => { :sign_up  => "register" }
  
  resources :customers do 
    collection do
        get :getcontacts
    end
      
    resources :contacts
  end
  
  resources :agents
  
  resources :commissions do
    collection do
      get :getcommission
    end
  end
  
  resources :settings
  resources :customer_search
  
  resources :currencies do
    collection do
      get :currentrate
    end
  end
  
  resources :exrates
  
  resources :orders do
    collection do
      post 'check'
      get 'walkin'
      post 'walkincreate'
    end
  end
  
  resources :purposes
  resources :income_sources
  resources :error
      
    
  root :to  => "orders#index"
  
  

end

app/models/currency.rb
# == Schema Information
# Schema version: 20100930135636
#
# Table name: currencies
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  country    :string(255)     not null
#  full_name  :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#

class Currency < ActiveRecord::Base
  has_many :exrates

  # Scope to find the current exchange rate for the currency
  #scope :currentrate, joins(:exrates).order("exrates.ex_rate_date DESC").limit(1)  

  # Validation begins 
  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 3 }
  validates :country, :presence  => true
  
  def current
    @rate = self.exrates.order("exrates.ex_rate_date DESC").first
    @rate.buy_rate
  end
end

app/controllers/currencies_controller.rb
# 
#  currencies_controller.rb
#  bosa
#  
#  Created by N.Subramanian on 2010-08-19.
#  Copyright 2010 N.Subramanian. All rights reserved.
# 

class CurrenciesController < ApplicationController
  respond_to :html
  
  def index
     @currencies = Currency.all
     
     flash[:error] = "No currency record is found in the system..." if @currencies.empty?
     
     respond_with(@currencies)
  end
  
  def new
    @currency = Currency.new
  end
  
  def create
    @currency = Currency.new(params[:currency])
    
    flash[:notice] = "New currency successfully created..." if @currency.save
    respond_with(@currency)
  end
  
  def show
    @currency = Currency.find(params[:id]) 
    
    respond_with(@currency)    
  end
  
  def edit
    @currency = Currency.find(params[:id])
    
    respond_with(@currency)
  end
  
  def update
    @currency = Currency.find(params[:id])
    
    flash[:notice] = "Currency details successfully updated..." if @currency.update_attributes(params[:currency])
    
    respond_with(@currency)
    
  end
  
  def destroy
    @currency = Currency.find(params[:id])
    
    flash[:notice] = "Currency record successfully deleted..." if @currency.destroy
    
    respond_with(@currency)
  end
  
  def currentrate
    @currency = Currency.find(params[:id])
    
    @curr_ex_rate = @currency.current
    
    render :text => @curr_ex_rate
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
        <li><%= link_to "Cancel", currencies_path %></li>
    </ul>
<% end %>
<br>

<%= semantic_form_for @currency do |f| %>
  <%= f.inputs  do %>
    <%= f.input :name, :label => 'Currency name' %>
    <%= f.input :full_name, :label => 'Full name' %>
    <%= f.input :country, :as  => :country, :priority_countries => [ "Brunei Darussalam", "India", "Singapore" ] %>
  <% end -%>
  <span class="my_button">
    <%= f.submit %>
  </span>
<% end -%>

app/views/currencies/edit.html.erb
<h1>Edit currency details: <%= @currency.name %></h1>
<%= render :partial => 'form' %>

app/views/currencies/index.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
        <li><%= link_to "Create new currency", new_currency_path %></li><br /><hr><br />
        <li><%= link_to "Back", settings_url %></li>
        
    </ul>
<% end %>
<br>
<% if !@currencies.empty? %>
  <h1>Currencies </h1>
  <br>
  <table id="bosaTable" class="display" border="0" cellspacing="1" cellpadding="0">
    <thead>  
    <tr>
      <th>Symbol</th>
       <th>Full Name</th>
       <th>Country</th>
       <th></th>
    </tr>
    </thead>
    <tbody>
    <% @currencies.each do |currency| %>
     <tr>
       <td><%= link_to currency.name, currency %></td>
       <td><%= currency.full_name %></td>
       <td><%= currency.country %></td>
       <td><%= link_to "Edit", edit_currency_path(currency) %> <%= link_to "Destroy", currency, :method  => :delete, :confirm  => 'Are you sure to delete the currency record?' %></td>
        </tr>
   <% end %>
   </tbody>
  </table>
  <% end -%>

app/views/currencies/new.html.erb
<h1>Create a new currency</h1>
<%= render :partial => 'form' %>

app/views/currencies/show.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
        <li><%= link_to "Edit", edit_currency_path(@currency) %></li>
        <li><%= link_to "Back", settings_path %></li>
    </ul>
<% end %>

<br>
<h2>Currency Details</h2>
<table border="0" cellspacing="5" cellpadding="5">
  <tr><th>Currency Symbol: </th><td><%= @currency.name %></td> </tr>
  <tr><th>Full Name: </th><td><%= @currency.full_name %></td> </tr>
  <tr><th>Country: </th><td><%= @currency.country %></td> </tr>
</table>