config/routes.rb
Bosa::Application.routes.draw do |map|

  devise_for :users, :controllers  => {:registrations  => "registrations", :sessions  => "sessions", :passwords  => "passwords"}, :path_names  => { :sign_up  => "register" }
  
  resources :customers do 
    collection do
        get :getcontacts
    end
      
    resources :contacts
  end
  
  resources :agents
  
  resources :commissions do
    collection do
      get :getcommission
    end
  end
  
  resources :settings
  resources :customer_search
  
  resources :currencies do
    collection do
      get :currentrate
    end
  end
  
  resources :exrates
  
  resources :orders do
    collection do
      post 'check'
      get 'walkin'
      post 'walkincreate'
    end
  end
  
  resources :purposes
  resources :income_sources
  resources :error
      
    
  root :to  => "orders#index"
  
  

end

app/models/setting.rb
# == Schema Information
# Schema version: 20100807152434
#
# Table name: settings
#
#  id                  :integer         not null, primary key
#  company_name        :string(255)     not null
#  street              :string(255)     not null
#  city                :string(255)
#  postcode            :string(255)
#  country             :string(255)
#  telephone           :string(255)
#  mobile              :string(255)
#  email               :string(255)
#  website             :string(255)
#  business_license_no :string(255)
#  base_currency       :string(255)     not null
#  base_currency_name  :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#

class Setting < ActiveRecord::Base
  
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
    
    def index
      @setting = Setting.first
      
      flash[:error] = "No system settings found in the system.  Please create the settings" if @setting.nil?
    end
    
    def edit
      @setting = Setting.find(params[:id])
    end
    
    def update
      
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
        <li><%= link_to "Cancel", :back %></li>
    </ul>
<% end %>
<br>

<%= semantic_form_for @setting do |f| %>
  <%= f.inputs "Application Settings:" do %>
    <%= f.input :company_name %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :postcode %>
    <%= f.input :country, :as  => :country, :priority_countries => [ "Brunei Darussalam", "India", "Singapore" ] %>
    <%= f.input :telephone, :label  => "Telephone#" %>
    <%= f.input :mobile, :label  => "Mobile#" %>
    <%= f.input :email %>
    <%= f.input :website %>
    <%= f.input :business_license_no %>
    <%= f.input :base_currency %>
    <%= f.input :base_currency_name %>
  <% end -%>
  <span class="my_button">
    <%= f.submit %>
    <%= link_to "Cancel", :back %>
  </span>
<% end %>

app/views/settings/edit.html.erb
<h2>Edit application settings</h2>
<%= render :partial => 'form' %>

app/views/settings/index.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
      <% if !@setting.nil? %>
        <li><%= link_to "Edit", edit_setting_path(@setting) %></li><br /><hr><br />
      <% end -%>
        <li><%= link_to "Currency", currencies_path %></li>
        <li><%= link_to "Commission", commissions_path %></li>
        <li><%= link_to "Purposes", purposes_path %></li>
        <li><%= link_to "Income Sources", income_sources_path %></li>
    </ul>
<% end %>
<br>

<h2>System Settings</h2>
<% if @setting %>
  <table border="0" cellspacing="5" cellpadding="5">
    <tr><th>Company Name: </th><td><%= @setting.company_name %></td> </tr>
    <tr><th>Street: </th><td><%= @setting.street %></td> </tr>
    <tr><th>City: </th><td><%= @setting.city %></td> </tr>
    <tr><th>Postcode: </th><td><%= @setting.postcode %></td> </tr>
    <tr><th>Country: </th><td><%= @setting.country %></td> </tr>
    <tr><th>Telephone#: </th><td><%= @setting.telephone %></td> </tr>
    <tr><th>Mobile#: </th><td><%= @setting.mobile %></td> </tr>
    <tr><th>Email: </th><td><%= @setting.email %></td> </tr>
    <tr><th>Website: </th><td><%= @setting.website %></td> </tr>
    <tr><th>Business License No: </th><td><%= @setting.business_license_no %></td> </tr>
    <tr><th>Base Currency: </th><td><%= @setting.base_currency %></td> </tr>
    <tr><th>Base Currency Name: </th><td><%= @setting.base_currency_name %></td> </tr>
  </table>
<% end -%>