config/routes.rb
Bosa::Application.routes.draw do |map|

  devise_for :users, :controllers  => {:registrations  => "registrations", :sessions  => "sessions", :passwords  => "passwords"}, :path_names  => { :sign_up  => "register" }
  
  resources :customers do 
    collection do
        get :getcontacts
    end
      
    resources :contacts
  end
  
  resources :agents
  
  resources :commissions do
    collection do
      get :getcommission
    end
  end
  
  resources :settings
  resources :customer_search
  
  resources :currencies do
    collection do
      get :currentrate
    end
  end
  
  resources :exrates
  
  resources :orders do
    collection do
      post 'check'
      get 'walkin'
      post 'walkincreate'
    end
  end
  
  resources :purposes
  resources :income_sources
  resources :error
      
    
  root :to  => "orders#index"
  
  

end

app/models/customer.rb
# == Schema Information
# Schema version: 20101208103510
#
# Table name: customers
#
#  id              :integer         not null, primary key
#  name            :string(255)     not null
#  dob             :date
#  sex             :string(255)
#  street          :string(255)     not null
#  city            :string(255)     not null
#  district        :string(255)
#  postcode        :string(255)
#  country         :string(255)
#  position        :string(255)
#  ic_number       :string(255)
#  passport_number :string(255)
#  telephone       :string(255)     not null
#  mobile          :string(255)
#  email           :string(255)
#  active          :boolean         default(TRUE)
#  created_at      :datetime
#  updated_at      :datetime
#

class Customer < ActiveRecord::Base
  has_many :contacts
  has_many :orders
    
  validates_presence_of :name, :message => "can't be blank"
  validates_presence_of :ic_number, :message  => "can't be blank"
  validates_presence_of :passport_number, :message  => "can't be blank"
  validates_uniqueness_of :ic_number, :message => 'IC number already registered for another customer.'
  validates_uniqueness_of :passport_number, :message => 'Passport number already registered for another customer.'
  
end

app/controllers/customers_controller.rb
# 
#  customers_controller.rb
#  bosa
#  
#  Created by N.Subramanian on 2010-08-19.
#  Copyright 2010 N.Subramanian. All rights reserved.
# 

class CustomersController < ApplicationController
  #current_section("customers")
  
  #load_and_authorize_resource
    
  def index
    @customers = Customer.all
      if @customers.empty?
        flash[:error] = "No customer record found in the system."
      end
  end
  
  def show
    @customer = Customer.find(params[:id])
    @contacts = @customer.contacts.all
    flash[:error] = "No address found for this customer" if @contacts.empty?      
  end
    
  def new
    @customer = Customer.new    
    @customer.dob = Time.now.to_date
  end
  
  def create
    @customer = Customer.new(params[:customer])
    
    respond_to do |format|
      if @customer.save
        flash[:notice] = "New customer record successfully created..."
        format.html { redirect_to(@customer)  }
      else
        flash.now[:error] = "Unable to create the record."
        format.html { render :action => 'new' }
      end
    end
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    
    @customer = Customer.find(params[:id])
    
    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        flash[:notice] = "Customer details successfully updated..."
        format.html { redirect_to (@customer)  }
      else
        flash.now[:error] = "Unable to update the details. Please check the inline error messages."
        format.html { render :action => 'edit'}
      end
    end
  end
  
  def destroy
    @customer = Customer.find(params[:id])
    respond_to do |format|
      if @customer.destroy
        flash[:notice] = "Customer record successfully deleted..."
        #format.html { redirect_to(customers_path)}
      else
        flash[:error] = "Unable to delete the record."
        #format.html { redirect_to(customers_path) }
      end
      format.html { redirect_to(customers_path)}
    end
  end
  
  def getcontacts
    if !params[:id].empty?
      @customer = Customer.find(params[:id])
      @contacts = @customer.contacts.all
        
      respond_to do |format|
          format.js { render :partial => 'contacts' } unless @contacts.empty?
      end
    else
      render :text => 'Please select a customer from the list'
    end
  end
  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_contact_list.html.erb
<% unless @contacts.empty? %>
  <h2>Addresses</h2>
  <br>
  <table id="bosaTable" class="display" border="0" cellspacing="1" cellpadding="0">
    <thead>
      <tr>        
        <th>Contact Name</th>
        <th>Relationship</th>
        <th>Street</th>
        <th>City</th>
        <th>District</th>
        <th>State</th>
        <th>Country</th>
        <th>Mobile#</th>
        <th>Telephone#</th>
        <th></th>
        <th></th>        
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
       <tr>      	 
         <td><%= link_to contact.contact_person, customer_contact_path(contact) %></td>
         <td><%= contact.relationship %></td>
         <td><%= contact.street %></td>
         <td><%= contact.city %></td>
         <td><%= contact.district %></td>
         <td><%= contact.state %></td>
         <td><%= contact.country %></td>
         <td><%= contact.mobile %></td>
         <td><%= contact.telephone %></td>
         <td><%= link_to "Edit", edit_customer_contact_path(contact) %> <%= link_to "Destroy", customer_contact_path(contact), :method  => :delete, :confirm  => 'Are you sure to delete the address record?' %></td>
         <td><%= link_to "Make Order", new_order_path(:id => contact.id) %> </td>  
         </tr>
     <% end %>
   </tbody>
  </table>
<% end -%>

app/views/customers/_contacts.html.erb
<% unless @contacts.empty? %>
  <h3>Addresses</h3>
  <br>
  <table id="bosaTable" class="display" border="0" cellspacing="1" cellpadding="0">
    <thead>
      <tr>
        <th>Contact Name</th>
        <th>Relationship</th>
        <th>Street</th>
        <th>City</th>
        <th>District</th>
        <th>State</th>
        <th>Country</th>
        <th>Mobile#</th>
        <th>Telephone#</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
       <tr>
         <td><%= contact.contact_person %></td>
         <td><%= contact.relationship %></td>
         <td><%= contact.street %></td>
         <td><%= contact.city %></td>
         <td><%= contact.district %></td>
         <td><%= contact.state %></td>
         <td><%= contact.country %></td>
         <td><%= contact.mobile %></td>
         <td><%= contact.telephone %></td>
         <td><%= radio_button_tag "contact_id", contact.id %></td>
         </tr>
     <% end %>
   </tbody>
  </table>
<% end -%>

app/views/customers/_form.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
        <li><%= link_to "Cancel", customers_path %></li>
    </ul>
<% end %>
<br>

<%= semantic_form_for @customer do |f| %>
  <%= f.inputs "Personal details :" do %>
    <%= f.input :name %>
    <%= f.input :dob, :label  => "Date of birth", :as  => :datepicker %>
    <%= f.input :sex, :as  => :radio, :collection  => [ "Male", "Female" ]  %>
  <% end -%>
  <%= f.inputs "Contact details :" do %> 
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :postcode %>
    <%= f.input :district %>
    <%= f.input :country, :as  => :country, :priority_countries => [ "Brunei Darussalam", "India", "Singapore" ] %>
    <%= f.input :ic_number, :label  => "IC#" %>
    <%= f.input :passport_number, :label  => "Passport#" %>
    <%= f.input :telephone, :label  => "Telephone#" %>
    <%= f.input :mobile, :label  => "Mobile#" %>
    <%= f.input :email %>
    <%= f.input :active %>
  <% end -%>
  <span class="my_button">
    <%= f.submit %>
    <%= link_to "Cancel", customers_path %>
  </span>
<% end %>