config/routes.rb
Bosa::Application.routes.draw do |map|

  devise_for :users, :controllers  => {:registrations  => "registrations", :sessions  => "sessions", :passwords  => "passwords"}, :path_names  => { :sign_up  => "register" }
  
  resources :customers do 
    collection do
        get :getcontacts
    end
      
    resources :contacts
  end
  
  resources :agents
  
  resources :commissions do
    collection do
      get :getcommission
    end
  end
  
  resources :settings
  resources :customer_search
  
  resources :currencies do
    collection do
      get :currentrate
    end
  end
  
  resources :exrates
  
  resources :orders do
    collection do
      post 'check'
      get 'walkin'
      post 'walkincreate'
    end
  end
  
  resources :purposes
  resources :income_sources
  resources :error
      
    
  root :to  => "orders#index"
  
  

end

app/models/income_source.rb
class IncomeSource < ActiveRecord::Base
  has_many :orders
  
  validates :name, :presence => true
end
# == Schema Information
#
# Table name: income_sources
#
#  id          :integer         not null, primary key
#  name        :string(255)     not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/income_sources_controller.rb
class IncomeSourcesController < ApplicationController
  respond_to :html
  
  def index
    @sources = IncomeSource.all
    
    if @sources.empty?
      flash[:error] = 'No income source is defined in the system.'
    end
  
  end
  
  def new
    @source = IncomeSource.new    
  end
  
  def create
    #raise params.inspect
    @source = IncomeSource.new(params[:income_source])
    
    if @source.save
      flash[:notice] = 'New income source successfully saved.'
      redirect_to income_sources_path
    else
      flash[:error] = 'Unable to save the income source record. Please try again.'
      render :action => 'new'
    end
    
  end
  
  def show
    
  end

  def edit
    @source = IncomeSource.find(params[:id])
  end
  
  def update
    @source = IncomeSource.find(params[:id])
    
    if @source.update_attributes(params[:income_source])
      #flash[:notice] = 'Income source updated successfully'
      redirect_to income_sources_path, :notice => 'Income source updated successfully'
    else
      flash[:error] = 'Unablet o save income source record. Please try again'
      render :action => 'edit'
    end
  end
  
  def destroy
    @source = IncomeSource.find(params[:id])
    
    if @source.destroy
      flash[:notice] = 'Income source successfully deleted.'       
    else
      flash[:error] = 'Unable to delete income source record.  Please try again'
    end
    redirect_to income_sources_path
  end
end

app/helpers/income_sources_helper.rb
module IncomeSourcesHelper
end

app/views/income_sources/_form.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
        <li><%= link_to "Cancel", income_sources_path %></li>
    </ul>
<% end %>
<br>

<%= semantic_form_for @source do |f| %>
  <%= f.inputs  do %>
    <%= f.input :name, :input_html => { :style => "width:25em" } %>
    <%= f.input :description, :input_html => { :style => "width:30em" } %>
  <% end -%>
  <span class="my_button">
    <%= f.submit %>
  </span>
<% end -%>

app/views/income_sources/edit.html.erb
<h2>Edit income salary</h2>
<%= render :partial => 'form'%>

app/views/income_sources/index.html.erb
<% content_for :sidebar do %>
  <h3>Action Menu</h3>
    <ul class="navigation">
        <li><%= link_to "New Income Source", new_income_source_path %></li>
        <li><%= link_to "Back to Setting", settings_path%></li>
    </ul>
<% end %>
<br>

<% unless @sources.empty? %>
  <h1>Income Sources</h1>
  <br>
  <table id="bosaTable" class="display" border="0" cellspacing="1" cellpadding="0">
    <thead>  
	  	<tr>
	  	  <th>Income Source</th>
	  	  <th>Notes</th>
	  	  <th></th>
	  	<tr>
	</thead>  	  
	<tbody>
		<% @sources.each do |source| %>
			<tr>
				<td><%= source.name %></td>
				<td><%= source.description %></td>
				<td> <%= link_to "Edit", edit_income_source_path(source) %> <%= link_to "Destroy", source, :method  => :delete, :confirm  => 'Are you sure to delete the income source record?' %>
			</tr>
		<% end %>
	</tbody>
  </table>		
<% end %>

app/views/income_sources/new.html.erb
<h3>Create new income source</h3>
<%= render :partial => 'form' %>